"""
One connection helper, two dialects.

Everything in storage.py is written once, in SQLite flavour with ``?``
placeholders. This module makes that same SQL run against Postgres, so hosting
the app somewhere durable is a config change rather than a rewrite.

Which one you get depends on a single environment variable:

    CARTEL_DB_URL=postgresql://user:pass@host:5432/cartel   -> Postgres
    (unset)                                                 -> SQLite at CARTEL_DB

Nothing else in the codebase knows or cares which is in use.
"""
from __future__ import annotations

import os
import re
import sqlite3
from pathlib import Path

POSTGRES_PREFIXES = ("postgres://", "postgresql://", "postgresql+psycopg://")


def database_url() -> str | None:
    url = os.environ.get("CARTEL_DB_URL", "").strip()
    return url or None


# Bumped by anything that changes data. The stats memo keys on it, so a cached
# figure can never outlive the write that made it wrong - in the app, in the
# tests, or from the command line.
_writes = 0
_MUTATES = ("INSERT", "UPDATE", "DELETE", "ALTER", "CREATE", "DROP", "REPLACE")


def note_write(sql) -> None:
    global _writes
    if not isinstance(sql, str):
        return
    head = sql.lstrip().upper()
    if head.startswith(_MUTATES):
        _writes += 1


def data_version() -> int:
    return _writes


def is_postgres(url: str | None = None) -> bool:
    url = url if url is not None else database_url()
    return bool(url) and url.startswith(POSTGRES_PREFIXES)


def dialect() -> str:
    return "postgres" if is_postgres() else "sqlite"


# --------------------------------------------------------------------------
# SQL translation
# --------------------------------------------------------------------------

# Only the handful of things that genuinely differ. Everything else — the
# ON CONFLICT clauses, RETURNING, the view, the indexes — is already standard
# SQL that both engines accept.
_DDL_SUBS = [
    (re.compile(r"INTEGER PRIMARY KEY AUTOINCREMENT", re.I),
     "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
    (re.compile(r"\bREAL\b", re.I), "DOUBLE PRECISION"),
    (re.compile(r"CREATE VIEW IF NOT EXISTS", re.I), "CREATE OR REPLACE VIEW"),
]

_PLACEHOLDER = re.compile(r"""\?(?=(?:[^']*'[^']*')*[^']*$)""")


def translate_ddl(sql: str) -> str:
    """Schema DDL, SQLite flavour in, current dialect out."""
    if not is_postgres():
        return sql
    for pattern, replacement in _DDL_SUBS:
        sql = pattern.sub(replacement, sql)
    return sql


def translate_params(sql: str) -> str:
    """``?`` placeholders to ``%s``, leaving anything inside quotes alone."""
    if not is_postgres():
        return sql
    return _PLACEHOLDER.sub("%s", sql)


# --------------------------------------------------------------------------
# a connection that behaves like sqlite3's, whichever engine is underneath
# --------------------------------------------------------------------------

class _PgCursorWrapper:
    """Gives a psycopg cursor the two sqlite3 habits the codebase relies on."""

    def __init__(self, cursor):
        self._cur = cursor

    def fetchone(self):
        return self._cur.fetchone()

    def fetchall(self):
        return self._cur.fetchall()

    def __iter__(self):
        return iter(self._cur)

    def __getattr__(self, item):
        return getattr(self._cur, item)


class _PgConnection:
    """
    A psycopg connection wearing sqlite3's interface: execute() and
    executemany() straight off the connection, plus executescript().
    """

    def __init__(self, conn):
        self._conn = conn

    def execute(self, sql, params=()):
        note_write(sql)
        cur = self._conn.cursor()
        cur.execute(translate_params(sql), tuple(params) if params else None)
        return _PgCursorWrapper(cur)

    def executemany(self, sql, seq):
        note_write(sql)
        seq = list(seq)
        if not seq:
            return _PgCursorWrapper(self._conn.cursor())
        cur = self._conn.cursor()
        # named-style (:name) with dicts, or positional with tuples
        if isinstance(seq[0], dict):
            converted = re.sub(r":(\w+)", r"%(\1)s", sql)
            cur.executemany(converted, seq)
        else:
            cur.executemany(translate_params(sql), [tuple(r) for r in seq])
        return _PgCursorWrapper(cur)

    def executescript(self, sql):
        note_write(sql)
        with self._conn.cursor() as cur:
            cur.execute(translate_ddl(sql))
        return self

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        self._conn.close()

    @property
    def raw(self):
        """The underlying psycopg connection, for pandas.read_sql_query."""
        return self._conn


def open_connection(db_path: str | Path | None = None):
    """
    Open a connection to whichever database is configured.

    db_path is only used for SQLite; when CARTEL_DB_URL is set it is ignored.
    """
    url = database_url()
    if is_postgres(url):
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as exc:                     # pragma: no cover
            raise RuntimeError(
                "CARTEL_DB_URL points at Postgres but psycopg isn't installed. "
                "Run: pip install 'psycopg[binary]'"
            ) from exc
        if url.startswith("postgresql+psycopg://"):
            url = url.replace("postgresql+psycopg://", "postgresql://", 1)
        # prepare_threshold=None disables psycopg's automatic prepared
        # statements. Supabase's transaction pooler hands each transaction to
        # whichever backend is free, so a statement prepared on one connection
        # is unknown to the next - psycopg then re-prepares under a name that
        # already exists and Postgres raises DuplicatePreparedStatement.
        #
        # Nothing here runs often enough for prepared statements to matter, and
        # a pooled connection is what hosting gives you.
        # connect_timeout matters more than it looks. Without it psycopg waits
        # indefinitely, so a database that is paused, restarting or out of
        # connections leaves the app hanging on startup with no message at all -
        # which is indistinguishable from a crash, and impossible to diagnose.
        # Ten seconds, then say plainly what happened.
        try:
            return _PgConnection(psycopg.connect(
                url, row_factory=dict_row, prepare_threshold=None,
                connect_timeout=10))
        except Exception as exc:
            raise RuntimeError(
                f"Couldn't reach the hosted database within 10 seconds.\n\n"
                f"{exc}\n\n"
                f"Usually one of:\n"
                f"  - the Supabase project is paused or restarting "
                f"(check the dashboard and press Restore)\n"
                f"  - the connection string or password is wrong\n"
                f"  - too many connections are already open; restarting the "
                f"Supabase project clears them"
            ) from exc

    Path(db_path).parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(db_path))
    # sqlite3 hands back a plain connection rather than a wrapper, so the write
    # counter is fed by its own tracer instead.
    conn.set_trace_callback(note_write)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def pandas_connection(conn):
    """
    pandas wants the driver connection, not our wrapper. Postgres also needs
    ``?`` rewritten, which callers do via sql_for_pandas below.
    """
    return conn.raw if isinstance(conn, _PgConnection) else conn


def sql_for_pandas(sql: str) -> str:
    return translate_params(sql)


def read_sql(sql: str, conn, params=None):
    """
    pandas.read_sql_query that works on either dialect.

    On Postgres the rows are built by hand rather than handed to pandas: the
    app's connections use dict rows, which pandas' DBAPI path misreads as data
    (you get the column names back as the first record). Doing it here also
    avoids pandas' "only SQLAlchemy is tested" warning on every query.
    """
    import pandas as pd

    if isinstance(conn, _PgConnection):
        from psycopg.rows import tuple_row
        with conn.raw.cursor(row_factory=tuple_row) as cur:
            cur.execute(sql_for_pandas(sql), tuple(params) if params else None)
            columns = [d.name for d in cur.description]
            rows = cur.fetchall()
        return pd.DataFrame(rows, columns=columns)

    return pd.read_sql_query(sql, conn, params=params)
